config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy] do
      member do
        get :followings, :followers
      end
    end
  end
  resources :records
  resources :posts do
    member do
      get :my_post_index
    end
    resources :comments, shallow: true
  end
  resources :profiles, only: %i[show]
  get 'sample', to: 'static_pages#sample'
  root "static_pages#top"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def top; end
  def sample; end
end

app/views/static_pages/sample.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class="main-img col-12">
     <%= image_tag "main_image.png" %>
    </div>
  </div>
  <div class="row">
    <div class="text-center">
      <%= link_to t('.back'), root_path, class: "btn btn-custom col-2 mt-5 mb-3" %>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<% content_for :title, t('.title') %>
<div class="container">
  <div class="row">
    <div class="col-12 mx-auto">
      <div class="main-img mt-3">
        <%= image_tag "title_image.png" %>
      </div>
      <div class="row">
        <div class="d-flex justify-content-around col-12">
          <div class="sub-img mt-3 col-12 col-md-3">
            <%= image_tag "wfh_5.png" %>
          </div>           
          <div class="d-flex align-items-center col-12 col-md-4">
              <br>▶︎カレンダー形式で見やすい記録機能
              <br>▶︎活動時間に連動してカレンダーの色が変わる
          </div>
        </div>
      </div>
      <div class="row">
        <div class="d-flex justify-content-around col-12">
          <div class="sub-img mt-3 col-12 col-md-3">
            <%= image_tag "wfh_3.png" %>
          </div>           
          <div class="d-flex align-items-center col-12 col-md-4">
            <div class="center-block">
              <br>▶︎投稿機能で朝活仲間と繋がろう
              <br>▶︎楽しく活動をシェアしよう
            </div>
          </div>
        </div>
      </div>
   
      
      <div class="mt-5">
        <% if user_signed_in? %>
          <div class="text-center">
            <br>*ようこそ<%= current_user.name %>さん*
          </div>
          <div class="d-flex justify-content-around m-3">
            <%= link_to t('.record_new'), new_record_path, class: "btn btn-custom col-2" %>
          </div>
        <% else %>
          <div class="text-center">
            <%= link_to t('.click_to_sample'), sample_path %>
          </div>
          <div class="d-flex justify-content-around m-3">
            <%= link_to t('.login'), new_user_session_path, class: "btn btn-custom col-2" %>
            <%= link_to t('.sign_up'), new_user_registration_path, class: "btn btn-custom col-2" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>