config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy] do
      member do
        get :followings, :followers
      end
    end
  end
  resources :records
  resources :posts do
    member do
      get :my_post_index
    end
    resources :comments, shallow: true
  end
  resources :profiles, only: %i[show]
  get 'sample', to: 'static_pages#sample'
  root "static_pages#top"
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to  request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_relationship_btn.html.erb
<% if current_user != post.user %>
  <% if current_user.following?(post.user) %>
    <%= link_to "フォロー外す", user_relationships_path(post.user.id), data: {turbo_method: :delete} %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(post.user.id), data: {turbo_method: :post} %>
  <% end %>
<% end %>

app/views/relationships/_user.html.erb
<% @users.each do |user| %> 
  <div class="card my-1">
    <div class="card-body row align-items-center">
      <div class="col-2", id='avatar'>
        <% if user.avatar.present? %>
          <%= image_tag user.avatar.url, class:"rounded-circle border" %>
        <% else %>
          <%= image_tag "default_avatar.png", class: "rounded-circle border" %>
        <% end %>
      </div>
      <div class="col-4">
        <%= link_to user.name, profile_path(user.id) %>
      </div>
      <div class="col-6">
        <%= user.introduction %>
      </div>
    </div>
  </div>
<% end %>

app/views/relationships/followers.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class='col-md-8 col-sm-10 mx-auto'>
      <% if @users.present? %>
        <%= render 'relationships/user' %>
      <% else %>
      <div class="text-center mb-3">***フォローされているユーザーはいません***</div>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class='col-md-8 col-sm-10 mx-auto'>
      <% if @users.present? %>
        <%= render 'relationships/user' %>
      <% else %>
      <div class="text-center mb-3">***フォローしているユーザーはいません***</div>
      <% end %>
    </div>
  </div>
</div>