config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy] do
      member do
        get :followings, :followers
      end
    end
  end
  resources :records
  resources :posts do
    member do
      get :my_post_index
    end
    resources :comments, shallow: true
  end
  resources :profiles, only: %i[show]
  get 'sample', to: 'static_pages#sample'
  root "static_pages#top"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followee_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followee
  has_many :followers, through: :passive_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX },on: :create

  def own?(object)
    object.user_id == id
  end

  def follow(user)
    followings << user
  end

  def unfollow(user)
    followings.destroy(user)
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    profile_path(resource)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @posts = current_user.posts.last
    @records = current_user.records.all
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row row-cols-2">
    <div class="col-md-8 col-sm-10 mx-auto">
      <div class="card m-4">
        <div class="card-header">
          <%=t('.recently_record') %>
        </div>
        <div class="card-body">
          <%= month_calendar(attribute: :date, events: @records) do |date, records| %>
            <%= date.day %>
            <% records.each do |record| %>
              <div>
                <%= link_to record.content, record_path(record) %>
              </div>
            <% end %>
          <% end %>
          <div class='row text-center'>
            <div class='col'>
              <i class="bi bi-square-fill square1"></i>:1時間未満
            </div>
            <div class='col'>
              <i class="bi bi-square-fill square2"></i>:1時間〜
            </div>
            <div class='col'>
              <i class="bi bi-square-fill square3"></i>:2時間〜
            </div>
            <div class='col'>
              <i class="bi bi-square-fill square4"></i>:3時間〜
            </div>
          </div>
        </div>
      </div>

      <div class="card m-4">
        <div class="card-header">
          <%= t('.recently_post') %>
        </div>
        <div class="card-body">
          <div class='col-md-10 col-sm-10 mx-auto'>
            <% if @posts.present? %>
              <%= render @posts %>
            <% else %>
              <div class="text-center mb-3">**投稿がありません**</div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
  
    <div class="col-md-4 col-sm-10 mx-auto">
      <div class="card m-4">
        <div class="card-body">
          <div class="card-title text-center"><%= t('.profile') %></div>
          <div class="col-5 mx-auto", id='avatar'>
          <% if @user.avatar.present? %>
            <%= image_tag @user.avatar.url, class:"rounded-circle border" %>
          <% else %>
            <%= image_tag "default_avatar.png", class: "rounded-circle border" %>
          <% end %>
          </div>
          <div class="card-text">
            <div class="text-center">
              <%= link_to @user.name, profile_path(@user.id) %>
              <%= link_to edit_user_registration_path do %>
                <i class='bi bi-pencil-square'></i>
              <% end %>
            </div>
            <div class="text-center pb-3 border-bottom">
              <% if @user.introduction.present? %>
                <%= @user.introduction %>
              <% else %>
                <%= t('.introduction') %>
              <% end %>
            </div>
            <div class="d-flex justify-content-evenly">
              <%= t('.records') %>
              <%= link_to @user.records.length, records_path %>
            </div>
            <div class="d-flex justify-content-evenly">
              <%= t('.posts') %>
              <%= link_to @user.posts.length, my_post_index_post_path(@user.id) %>
            </div>
            <div class="d-flex justify-content-evenly">
              <%= t('.followings') %>
              <%= link_to @user.followings.length, followings_user_relationships_path(@user.id) %>
            </div>
            <div class="d-flex justify-content-evenly">
              <%= t('.followers') %>
              <%= link_to @user.followers.length, followers_user_relationships_path(@user.id) %>
            </div>
          </div>
        </div>
      </div>

      <div class="card m-4">
        <div class="card-header">
          <%= t('.line_alarm') %>
        </div>
        <div class="card-body">
          <div class='text-center'><%= t('.setting_time') %></div>
          <div class='text-center'>
            <%= link_to t('.setting'), '#', class: 'btn btn-custom col-8' %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>