config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :users, only: %i[index show] do
    resource :relationships, only: %i[create destroy] do
      member do
        get :followings, :followers
      end
    end
  end
  resources :records
  resources :posts do
    member do
      get :my_post_index
    end
    resources :comments, shallow: true
  end
  resources :profiles, only: %i[show]
  get 'sample', to: 'static_pages#sample'
  root "static_pages#top"
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :post, dependent: :destroy

  validates :date, presence: true
  validates :started_time, presence: true
  validates :finished_time, presence: true
  validates :content, presence: true, length: { maximum: 25 }
  validates :memo, length: { maximum: 65_535 }

  def active_time
    if self.finished_time >= self.started_time
      active_time = self.finished_time - self.started_time
    else
      active_time = (self.finished_time - self.started_time) + (24 * 60 * 60)
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @records = current_user.records.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      redirect_to records_path, success: t('flash_message.created', item: Record.model_name.human)
    else
      flash.now[:danger] = t('flash_message.not_created', item: Post.model_name.human)
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = current_user.records.find(params[:id])
    if @record.update(record_params)
      redirect_to record_path(@record), success: t('flash_message.updated', item: Record.model_name.human)
    else
      flash.now[:danger] = t('flash_message.updated', item: Record.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    record = current_user.records.find(params[:id])
    record.destroy!
    redirect_to records_path, status: :see_other, success: "削除しました"
  end


  def start_time
    self.date
  end
  private

  def record_params
    params.require(:record).permit(:date, :started_time, :finished_time, :content, :memo)
  end

end

app/helpers/records_helper.rb
module RecordsHelper
  def color_of_active_day(record)
    if record.active_time >= 3 * 60 * 60
      return '#FF9B78'
    elsif record.active_time >= 2 * 60 * 60
      return '#FFB290'
    elsif record.active_time >= 1 * 60 * 60
      return '#FFC8A7'
    else
      return '#FFDFBE'
    end
  end
end

app/views/records/_form.html.erb
<%= form_with model: @record, local: true do |f| %>
    <%= render 'shared/error_message', object: f.object  %>
      <div class= 'form_group'>
      <%= f.label :date %>
      <%= f.date_select :date, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :started_time %>
      <%= f.time_select :started_time, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :finished_time %>
      <%= f.time_select :finished_time, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :memo %>
      <%= f.text_area :memo, class: 'form-control', size: "40x10" %>
    </div>
    <%= f.submit nil, class: 'btn btn-custom col-2 mt-2' %>
  <% end %>
   

app/views/records/edit.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-10 mx-auto">
      <%= render 'records/form' %>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <%= month_calendar(attribute: :date, events: @records) do |date, records| %>
        <%= date.day %>
        <% records.each do |record| %>
          <div>
            <%= link_to record.content, record_path(record) %>
          </div>
        <% end %>
      <% end %>
        <div class='row text-center'>
          <div class='col'>
            <i class="bi bi-square-fill square1"></i>:1時間未満
          </div>
          <div class='col'>
            <i class="bi bi-square-fill square2"></i>:1時間〜
          </div>
          <div class='col'>
            <i class="bi bi-square-fill square3"></i>:2時間〜
          </div>
          <div class='col'>
            <i class="bi bi-square-fill square4"></i>:3時間〜
          </div>
        </div>
 
        <div class="mt-3">
          <div class="d-flex justify-content-around">
            <%= link_to t('.new'), new_record_path, class: 'btn btn-custom col-2' %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/records/new.html.erb
<% content_for :title, t('.title') %>
<h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-10 mx-auto">
      <%= render 'records/form' %>
    </div>
  </div>
</div>

app/views/records/show.html.erb
<% content_for :title, t('.title') %>
<div class="container">
  <h2 class="text-center mt-4 mb-3"><%= t('.title') %></h2>
  <div class="col-md-8 col-sm-10 mx-auto">
    <ul>
      <li>日付：<%= @record.date %></li>
      <li>開始時刻：<%= l @record.started_time, format: :time %></li>
      <li>終了時刻：<%= l @record.finished_time, format: :time %></li>
    </ul>
    <p>活動内容:
    <div class='card col-7'>
      <div class="card-body">
        <p class='card-text'><%= simple_format(@record.content) %>
      </div>
    </div>
    <p>メモ:
    <div class='card'>
      <div class="card-body">
        <p class='card-text'><%= simple_format(@record.memo) %>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-2">
  <%= link_to t('.edit'), edit_record_path(@record), class: 'btn btn-custom col-2' %>
</div>
<div class="d-flex justify-content-center mt-2">
  <%= link_to t('.destroy'), record_path(@record), class: 'btn btn-custom col-2', data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_caution') } %>
</div>
<div class="d-flex justify-content-center mt-5">
  <%= link_to t('.back'), records_path, class: 'btn btn-custom col-2' %>
</div>